{% set name = "pygments_pytest" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 018d2b8c5afeb9e9d853d2540c0de9f5fd45563b061533713ded7a2558900850

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments
    - python >=3.6

test:
  imports:
    - pygments_pytest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygments-pytest/
  summary: A pygments lexer for pytest output.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
