{% set name = "pygments_pytest" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 564b1a9bb9d254b93586361cf26a58011d71c66f8af20c33eaf5c3505e35ef28

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments
    - python >=3.6

test:
  imports:
    - pygments_pytest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygments-pytest/
  summary: A pygments lexer for pytest output.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
